- hosts: all
  sudo: no
  #vars_files:
    #- vars/defaults.yml
  vars:
  tasks:
    # - { include: tasks/setup_sudo.yml }
    # - { include: tasks/create_user.yml user=mike primary_group=mike additional_groups=wheel }

    - name: Install git,tmux,irssi,cpanminus
      yum: name={{ item.name }} state=latest
      with_items:
        - name: zsh
        - name: wget
        - name: curl
        - name: git
        - name: tmux
        - name: irssi
        #-  name: 'cpanminus'
      sudo: yes
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: Install Security Upgrades for Debian
      apt:
        upgrade=safe
        update_cache=yes
        cache_valid_time=86400
      sudo: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Install git,tmux,irssi,cpanminus
      apt:
        pkg={{ item.name }}
        state=latest
      with_items:
        - name: zsh
        - name: wget
        - name: curl
        - name: git
        - name: tmux
        - name: irssi
        #-  name: 'cpanminus'
      sudo: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Setup GOPATH Tree
      file: path=/home/{{ ansible_ssh_user }}/Development/go/{{ item.name }} state=directory
      with_items:
        - { name: 'bin' }
        - { name: 'pkg' }
        - { name: 'src' }

    - name: Check for dotfile changes
      git:
        repo=git@github.com:Kusold/dotfiles.git
        dest=/home/{{ ansible_ssh_user }}/dotfiles
        accept_hostkey=yes
      notify:
        - generate symlinks

    - name: Set user's shell to zsh
      user:
        name={{ ansible_ssh_user }}
        shell=/bin/zsh
      sudo: yes

      # may need to run "sudo cpanm install Bundle::LWP" && "sudo cpanm install Lingua::Ispell" for scriptassist
    #- include: tasks/install_nodejs.yml

  handlers:
    - name: generate symlinks
      shell: bash /home/{{ ansible_ssh_user }}/dotfiles/symlink-files.sh

    - name: set file owner
      file:
        path=/home/{{ansible_ssh_user}}/.ssh/known_hosts
        owner={{ansible_ssh_user}}
        group={{ansible_ssh_user}}
        mode=644
      sudo: yes

  roles:
    - { role: joshualund.golang, go_tarball: go1.4.2.linux-amd64.tar.gz, go_tarball_checksum: 141b8345932641483c2437bdbd65488a269282ac85f91170805c273f03dd223b, sudo: yes }
